### PR TITLE
Fix FreeBSD build

### LINKED ISSUE #294: `swift build` fails on FreeBSD
## Summary

`swift build` fails on FreeBSD.

- FreeBSD 15.0-RELEASE-p1 x86_64
- Swift version 6.3-dev (LLVM b58b2a34d509492, Swift cf535d8b998d09b) ([Swift on FreeBSD Preview](https://forums.swift.org/t/swift-on-freebsd-preview/83064))
  - Target: x86_64-unknown-freebsd14.3
  - Build config: +assertions
- swift-system main branch 7e474cb4bdde782a94c3568d961265b5c6bf439d

## Error logs

Initial state:

```console
$ swift build --build-tests
...
/home/kebo/swift-system/Sources/System/Internals/Constants.swift:697:33: error: cannot convert return expression of type 'Int32' to return type 'mode_t' (aka 'UInt16')
695 | #if SYSTEM_PACKAGE_DARWIN || os(FreeBSD)
696 | @_alwaysEmitIntoClient
697 | internal var _S_IFWHT: mode_t { S_IFWHT }
    |                                 `- error: cannot convert return expression of type 'Int32' to return type 'mode_t' (aka 'UInt16')
698 | #endif
699 | 

[#ImplementationOnlyDeprecated]: <https://docs.swift.org/compiler/documentation/diagnostics/implementation-only-deprecated>
/home/kebo/swift-system/Sources/System/Internals/Constants.swift:697:33: error: cannot convert return expression of type 'Int32' to return type 'mode_t' (aka 'UInt16')
695 | #if SYSTEM_PACKAGE_DARWIN || os(FreeBSD)
696 | @_alwaysEmitIntoClient
697 | internal var _S_IFWHT: mode_t { S_IFWHT }
    |                                 `- error: cannot convert return expression of type 'Int32' to return type 'mode_t' (aka 'UInt16')
698 | #endif
699 |
...
```

After fixing the error above:

```console
$ swift build --build-tests
...
/home/kebo/swift-system/Tests/SystemTests/StatTests.swift:372:19: error: type 'FileFlags' has no member 'tracked'
370 |       let userSettableFlags: FileFlags = [
371 |         .noDump, .userImmutable, .userAppend,
372 |         .opaque, .tracked, .hidden,
    |                   `- error: type 'FileFlags' has no member 'tracked'
373 |         .userNoUnlink,
374 |         .offline,
...
```

After fixing the error above:

```console
$ swift build --build-tests
...
/home/kebo/swift-system/Tests/SystemTests/StatTests.swift:387:48: error: cannot convert value of type 'CInterop.FileFlags' (aka 'UInt32') to expected argument type 'UInt'
385 | 
386 |       flags.insert(userSettableFlags)
387 |       try #require(fchflags(fd.rawValue, flags.rawValue) == 0, "\(Errno.current)")
    |                                                `- error: cannot convert value of type 'CInterop.FileFlags' (aka 'UInt32') to expected argument type 'UInt'
388 | 
389 |       stat = try fd.stat()
...
```

After fixing the error above:

```console
$ swift build --build-tests
...
/home/kebo/swift-system/Tests/SystemTests/StatTests.swift:393:48: error: cannot convert value of type 'CInterop.FileFlags' (aka 'UInt32') to expected argument type 'UInt'
391 | 
392 |       flags.remove(userSettableFlags)
393 |       try #require(fchflags(fd.rawValue, flags.rawValue) == 0, "\(Errno.current)")
    |                                                `- error: cannot convert value of type 'CInterop.FileFlags' (aka 'UInt32') to expected argument type 'UInt'
394 | 
395 |       stat = try fd.stat()
...
```

### LINKED ISSUE #295: `swift test` fails on FreeBSD
## Summary

`swift test` fails on FreeBSD.

- FreeBSD 15.0-RELEASE-p1 x86_64
- Swift version 6.3-dev (LLVM b58b2a34d509492, Swift cf535d8b998d09b) ([Swift on FreeBSD Preview](https://forums.swift.org/t/swift-on-freebsd-preview/83064))
  - Target: x86_64-unknown-freebsd14.3
  - Build config: +assertions
- swift-system main branch 7e474cb4bdde782a94c3568d961265b5c6bf439d

## Logs

After fixing #293:

```console
$ swift test
...
Test Suite 'debug.xctest' passed at 2026-01-28 20:35:29.778
         Executed 52 tests, with 0 failures (0 unexpected) in 2.013 (2.013) seconds
Test Suite 'All tests' passed at 2026-01-28 20:35:29.778
         Executed 52 tests, with 0 failures (0 unexpected) in 2.013 (2.013) seconds
◇ Test run started.
↳ Testing Library Version: 6.3-dev (98430f2d6cb8d81)
↳ Target Platform: x86_64-unknown-freebsd
◇ Suite "Stat" started.
◇ Suite "FileMode" started.
◇ Test permissions() started.
◇ Test followSymlinkInits() started.
◇ Test flags() started.
◇ Test basics() started.
◇ Test times() started.
◇ Test basics() started.
◇ Test invalidInput() started.
✔ Test invalidInput() passed after 0.001 seconds.
✔ Test basics() passed after 0.001 seconds.
✔ Suite "FileMode" passed after 0.001 seconds.
✔ Test permissions() passed after 0.003 seconds.
✔ Test basics() passed after 0.003 seconds.
✘ Test flags() recorded an issue at StatTests.swift:387:11: Expectation failed: (fchflags(fd.rawValue, UInt(flags.rawValue)) → -1) == 0
↳ Operation not supported
✘ Test flags() failed after 0.004 seconds with 1 issue.
✘ Test followSymlinkInits() recorded an issue at StatTests.swift:121:7: Expectation failed: (symlinkStat.sizeAllocated → 512) < (targetStat.sizeAllocated → 512)
✘ Test followSymlinkInits() failed after 0.004 seconds with 1 issue.
✔ Test times() passed after 0.043 seconds.
✘ Suite "Stat" failed after 0.043 seconds with 2 issues.
✘ Test run with 7 tests in 2 suites failed after 0.044 seconds with 2 issues.
```

```
✘ Test flags() recorded an issue at StatTests.swift:387:11: Expectation failed: (fchflags(fd.rawValue, UInt(flags.rawValue)) → -1) == 0
↳ Operation not supported
```

This occurs since I use ZFS as a root file system. `UF_IMMUTABLE`, `UF_APPEND`, `UF_OPAQUE`, `UF_NOUNLINK`, and `UF_REPARSE` are not supported on ZFS. Although this may pass successfully on other file systems, ZFS is popular on FreeBSD. Thus, those flags should be omitted from the test case for FreeBSD.

https://github.com/openzfs/zfs/blob/a157ef62a16814459f925f14fe1b759bd4f8338d/module/os/freebsd/zfs/zfs_vnops_os.c#L5410-L5413

```
✘ Test followSymlinkInits() recorded an issue at StatTests.swift:121:7: Expectation failed: (symlinkStat.sizeAllocated → 512) < (targetStat.sizeAllocated → 512)
```

On FreeBSD, the value of `st_blocks` of a symlink is usually not zero. On the other hand, on linux, it is.

### PR DESCRIPTION
**Pull request by kkebo**
fixes #294, fixes #295

This PR fixes `swift build` and `swift test` on FreeBSD.

```console
$ swift build
[1/1] Planning build
Building for debugging...
[1/1] Write swift-version-2B7A02F0DA2902A5.txt
Build complete! (0.14s)
$ swift test
Building for debugging...                                                                                                                                                              
[5/5] Compiling SystemTests StatTests.swift                                                                                                                                            
Build complete! (1.84s)                                                                                                                                                                
Test Suite 'All tests' started at 2026-01-28 00:02:35.756                                                                                                                              
Test Suite 'debug.xctest' started at 2026-01-28 00:02:35.758
...
Test Suite 'debug.xctest' passed at 2026-01-28 00:02:37.857
         Executed 52 tests, with 0 failures (0 unexpected) in 2.099 (2.099) seconds
Test Suite 'All tests' passed at 2026-01-28 00:02:37.857
         Executed 52 tests, with 0 failures (0 unexpected) in 2.099 (2.099) seconds
◇ Test run started.
↳ Testing Library Version: 6.3-dev (98430f2d6cb8d81)
↳ Target Platform: x86_64-unknown-freebsd
◇ Suite "Stat" started.
◇ Suite "FileMode" started.
◇ Test basics() started.
◇ Test times() started.
◇ Test permissions() started.
◇ Test followSymlinkInits() started.
◇ Test invalidInput() started.
◇ Test basics() started.
◇ Test flags() started.
✔ Test invalidInput() passed after 0.001 seconds.
✔ Test basics() passed after 0.001 seconds.
✔ Suite "FileMode" passed after 0.001 seconds.
✔ Test flags() passed after 0.003 seconds.
✔ Test basics() passed after 0.004 seconds.
✔ Test permissions() passed after 0.004 seconds.
✔ Test followSymlinkInits() passed after 0.004 seconds.
✔ Test times() passed after 0.043 seconds.
✔ Suite "Stat" passed after 0.044 seconds.
✔ Test run with 7 tests in 2 suites passed after 0.044 seconds.
```

Environment:

```console
$ uname -a
FreeBSD Coconut-rhinoceros-beetle 15.0-RELEASE-p1 FreeBSD 15.0-RELEASE-p1 releng/15.0-n280999-7bceec30b351 GENERIC amd64
$ swift --version
Swift version 6.3-dev (LLVM b58b2a34d509492, Swift cf535d8b998d09b)
Target: x86_64-unknown-freebsd14.3
Build config: +assertions
```

Swift toolchain is from [forums.swift.org/t/swift-on-freebsd-preview/83064](https://forums.swift.org/t/swift-on-freebsd-preview/83064).

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

File: Tests/SystemTests/StatTests.swift [hunk 1]
```diff
@@ -417,4 +418,11 @@ private func == (lhs: timespec, rhs: timespec) -> Bool {
   lhs.tv_sec == rhs.tv_sec && lhs.tv_nsec == rhs.tv_nsec
 }
 
+#if os(FreeBSD)
+// Helper functions for FreeBSD
```
Comment (glessard) [inline Tests/SystemTests/StatTests.swift]: It would be fine to have the correct direct call to `fchflags` inside an `#if` statement in the test case itself.

File: Tests/SystemTests/StatTests.swift [hunk 2]
```diff
@@ -118,7 +118,11 @@ private struct StatTests {
       #expect(targetStat.type == .regular)
       #expect(symlinkStat.type == .symbolicLink)
       #expect(symlinkStat.size < targetStat.size)
+      #if os(FreeBSD)
+      #expect(symlinkStat.sizeAllocated <= targetStat.sizeAllocated)
```
Comment (glessard) [inline Tests/SystemTests/StatTests.swift]: I think that the formulation with `<=` would be fine for all posix platforms. Let's just switch to that rather than conditionalizing the test.

File: Tests/SystemTests/StatTests.swift [hunk 3]
```diff
@@ -384,13 +381,15 @@ private struct StatTests {
       #endif
 
       flags.insert(userSettableFlags)
-      try #require(fchflags(fd.rawValue, flags.rawValue) == 0, "\(Errno.current)")
+      // On FreeBSD, the second argument of `fchflags` requires `UInt` instead of`UInt32`.
+      try #require(fchflags(fd.rawValue, .init(flags.rawValue)) == 0, "\(Errno.current)")
```
Comment (glessard) [inline Tests/SystemTests/StatTests.swift]: In the fullness of time, the right solution will be to have a proper wrapper of `chflags` and `fchflags` that take a `FileFlags` parameter. This is good in the meantime.

**Review by glessard — APPROVED** [review]
